### ISSUE TITLE
I installed Forge Mod, but it says I need Fabric API.

### ISSUE THREAD

**Issue by hyoungjink** [Snownee/PinTooltips#1]
### Mod loader

Please select

### Minecraft version

1.20.1

### Mod version

1.0.0

### Modloader version

forge 47.3.7

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

![image](https://github.com/user-attachments/assets/a668109e-31ce-4db1-9a38-46504e1be999)

**Comment by SettingDust** [comment]
https://modrinth.com/mod/forgified-fabric-api/versions
plz
